[package]
name = "openworkers-transform"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
swc_common = "18.0.1"
swc_ecma_ast = "20.0.1"
swc_ecma_parser = "33.0.1"
swc_ecma_transforms_typescript = "40.0.0"
swc_ecma_transforms_base = "36.0.1"
swc_ecma_codegen = "23.0.0"
swc_ecma_visit = "20.0.0"
